name = input('Qual o nome do aluno? ')
materia1 = input("Qual materia? ")
bimestre1 = input('Qual bimestre estamos? ')
n = float(input('Qual a nota do aluno na av1? '))
n2 = float(input('Qual a nota do aluno na av2? '))
n3 = float(input('Qual a nota do aluno no tb1? '))
n4 = float(input('Qual a nota do aluno no tb2? '))
m1 = float(n + n2 + n3 + n4)
m2 = float(m1 / 4)
print(f'A média do aluno {name} no  bimestre {bimestre1} será {m2} ')
if float(m2 >= 6):
    print("Aprovado!")
if float(m2 < 6):
    print('Reprovado!')
bimestre2 = input('Qual bimestre estamos? ')
n5 = float(input('Qual a nota do aluno na av1? '))
n6 = float(input('Qual a nota do aluno na av2? '))
n7 = float(input('Qual a nota do aluno no tb1? '))
n8 = float(input('Qual a nota do aluno no tb2? '))
m3 = float(n5 + n6 + n7 + n8)
m4 = float(m3 / 4)
print(f'A média do aluno {name} no  bimestre {bimestre2} será {m4} ')
if float(m4 >= 6):
    print("Aprovado!")
if float(m4 < 6):
    print('Reprovado!', end="")
    bimestre3 = input('Qual bimestre estamos? ')
    n9 = float(input('Qual a nota do aluno na av1? '))
    n10 = float(input('Qual a nota do aluno na av2? '))
    n11 = float(input('Qual a nota do aluno no tb1? '))
    n12 = float(input('Qual a nota do aluno no tb2? '))
    m5 = float(n9 + n10 + n11 + n12)
    j6: float = (m5 / 4)
    print(f'A média do aluno {name} no  bimestre {bimestre3} será {j6} ')
    if float(j6 >= 6):
        print("Aprovado!")
    if float(j6 < 6):
        print('Reprovado!')
bimestre4 = input('Qual bimestre estamos? ')
n13 = float(input('Qual a nota do aluno na av1? '))
n14 = float(input('Qual a nota do aluno na av2? '))
n15 = float(input('Qual a nota do aluno no tb1? '))
n16 = float(input('Qual a nota do aluno no tb2? '))
m7 = float(n13 + n14 + n15 + n16)
m8 = float(m7 / 4)
print(f'A média do aluno {name} no  bimestre {bimestre4} será {m8} ')
if float(m8 >= 6):
 print("Aprovado!")
if float(m8 < 6):
    print('Reprovado!')
bimestref = float (m2 + m4 + j6 + m8)
